return {
  "folke/which-key.nvim",
  lazy = false,
  opts = {},
  config = function(_, opts)
    local wk = require("which-key")
    wk.setup(opts)
    wk.register({
      -- { "",           group = "Debug" },
      -- { "",           group = "Cheatsheet" },
      -- { "",           group = "Angular" },
      -- { "",           group = "Trouble" },
      -- { "",           group = "Lazy" },
      -- { "",           desc = "Lazy Sync" },
      -- { "",           desc = "Lazy" },
      -- { "",           group = "Todo" },
      -- { "",           group = "Utils" },
      -- { "",           group = "Trouble Lsp" },
      -- { "",           group = "Projects" },
      -- { "",           group = "Git" },
      -- { "",           group = "Telescope" },
      -- { "",           group = "Lsp" },
      -- { "",           group = "Nx" },
      -- { "",           group = "Terminal" },
      -- { "",           group = "Rest Client" },
      -- { "<leader>?",  group = "Cheatsheet" },
      -- { "<leader>L",  group = "Lazy" },
      -- { "<leader>Ll", function() vim.cmd([[Lazy]]) end,      desc = "Lazy" },
      -- { "<leader>Ls", function() vim.cmd([[Lazy sync]]) end, desc = "Lazy Sync" },
      -- { "<leader>T",  group = "Todo" },
      -- { "<leader>a",  group = "Angular" },
      -- { "<leader>c",  group = "Trouble Lsp" },
      -- { "<leader>d",  group = "Debug" },
      -- { "<leader>f",  group = "Telescope" },
      -- { "<leader>g",  group = "Git" },
      -- { "<leader>l",  group = "Lsp" },
      -- { "<leader>n",  group = "Nx" },
      -- { "<leader>p",  group = "Projects" },
      -- { "<leader>r",  group = "Rest Client" },
      -- { "<leader>t",  group = "Terminal" },
      -- { "<leader>u",  group = "Utils" },
      -- { "<leader>x",  group = "Trouble" },
      ["<leader>"] = {
        ["?"] = { name = "Cheatsheet" },
        a = { name = "Angular" },
        c = { name = "Trouble Lsp" },
        n = { name = "Nx" },
        f = { name = "Telescope" },
        l = { name = "Lsp" },
        L = {
          name = "Lazy",
          l = { function() vim.cmd([[Lazy]]) end, "Lazy" },
          s = { function() vim.cmd([[Lazy sync]]) end, "Lazy Sync" },
        },
        d = { name = "Debug" },
        g = { name = "Git" },
        t = { name = "Terminal" },
        u = { name = "Utils" },
        p = { name = "Projects" },
        x = { name = "Trouble" },
        r = { name = "Rest Client" },
        T = { name = "Todo" }
      },
    })
  end
}
